export const DEVICE_ASPECT_RATIOS = [
  {
    name: "Desktop - Huge",
    width: 2880,
    height: 1800,
    ratio: 2,
    type: "desktop",
  },
  {
    name: "Desktop - Extra Large",
    width: 1920,
    height: 1080,
    ratio: 1,
    type: "desktop",
  },
  {
    name: "Desktop - Large",
    width: 1440,
    height: 900,
    ratio: 1,
    type: "desktop",
  },
  {
    name: "Desktop - HiDPI",
    width: 1366,
    height: 768,
    ratio: 1,
    type: "desktop",
  },
  {
    name: "Desktop - MDPI",
    width: 1280,
    height: 800,
    ratio: 1,
    type: "desktop",
  },
  {
    name: "Laptop with HiDPI screen",
    width: 1440,
    height: 900,
    ratio: 2,
    type: "desktop",
  },
  {
    name: "Laptop with MDPI screen",
    width: 1280,
    height: 800,
    ratio: 1,
    type: "desktop",
  },
  {
    name: "Laptop with touch",
    width: 1280,
    height: 950,
    ratio: 1,
    type: "desktop",
  },
  {
    name: "Tablet - Portrait",
    width: 768,
    height: 1024,
    ratio: 1,
    type: "tablet",
  },
  {
    name: "Tablet - Landscape",
    width: 1024,
    height: 768,
    ratio: 1,
    type: "tablet",
  },
  {
    name: "Google Nexus 10",
    width: 1280,
    height: 800,
    ratio: 2,
    type: "tablet",
  },
  { name: "Apple iPad", width: 1024, height: 768, ratio: 2, type: "tablet" },
  {
    name: "Apple iPad Mini",
    width: 1024,
    height: 768,
    ratio: 1,
    type: "tablet",
  },
  {
    name: "Amazon Kindle Fire HDX",
    width: 2560,
    height: 1600,
    ratio: 2,
    type: "mobile",
  },

  { name: "iPhone 4", width: 320, height: 480, ratio: 2, type: "mobile" },
  { name: "iPhone 5", width: 320, height: 568, ratio: 2, type: "mobile" },
  { name: "iPhone X", width: 375, height: 812, ratio: 3, type: "mobile" },
  { name: "iPhone 8 Plus", width: 414, height: 736, ratio: 3, type: "mobile" },
  { name: "iPhone 8", width: 375, height: 667, ratio: 2, type: "mobile" },
  { name: "iPhone 7 Plus", width: 414, height: 736, ratio: 3, type: "mobile" },
  { name: "iPhone 6s Plus", width: 375, height: 667, ratio: 3, type: "mobile" },
  { name: "iPhone 6 Plus", width: 375, height: 667, ratio: 3, type: "mobile" },
  { name: "iPhone 7", width: 375, height: 667, ratio: 2, type: "mobile" },
  { name: "iPhone 6s", width: 375, height: 667, ratio: 2, type: "mobile" },
  { name: "iPhone 6", width: 375, height: 667, ratio: 2, type: "mobile" },
  { name: "iPhone SE", width: 320, height: 568, ratio: 2, type: "mobile" },
  {
    name: "iPad Pro 12.9-inch",
    width: 1024,
    height: 1366,
    ratio: 2,
    type: "tablet",
  },
  {
    name: "iPad Pro 10.5-inch",
    width: 1112,
    height: 834,
    ratio: 2,
    type: "tablet",
  },
  {
    name: "iPad Pro 9.7-inch",
    width: 768,
    height: 1024,
    ratio: 2,
    type: "tablet",
  },
  { name: "iPad Air 2", width: 768, height: 1024, ratio: 2, type: "tablet" },
  { name: "iPad Mini 4", width: 768, height: 1024, ratio: 2, type: "tablet" },

  { name: "Google Nexus 4", width: 384, height: 640, ratio: 2, type: "mobile" },
  { name: "Google Nexus 5", width: 360, height: 640, ratio: 3, type: "mobile" },
  {
    name: "Google Nexus 6",
    width: 412,
    height: 732,
    ratio: 3.5,
    type: "mobile",
  },
  { name: "Google Nexus 7", width: 960, height: 600, ratio: 2, type: "mobile" },
  {
    name: "Samsung Galaxy Note 3",
    width: 360,
    height: 640,
    ratio: 3,
    type: "mobile",
  },
  {
    name: "Samsung Galaxy Note II",
    width: 360,
    height: 640,
    ratio: 2,
    type: "mobile",
  },
  {
    name: "Samsung Galaxy S III",
    width: 360,
    height: 640,
    ratio: 2,
    type: "mobile",
  },
  {
    name: "Samsung Galaxy S4",
    width: 360,
    height: 640,
    ratio: 3,
    type: "mobile",
  },
];
